// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: zmq_protocol.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Tyr.Common.Data.Robot
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ImuStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"accel_x")]
        public float AccelX { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"accel_y")]
        public float AccelY { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"accel_z")]
        public float AccelZ { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"gyro_x")]
        public float GyroX { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"gyro_y")]
        public float GyroY { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"gyro_z")]
        public float GyroZ { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MotorState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        public float Target { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"actual")]
        public float Actual { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"motion_mode")]
        public MotionMode MotionMode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MotorStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"enabled")]
        public bool Enabled { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"motors")]
        public global::System.Collections.Generic.List<MotorState> Motors { get; } = new global::System.Collections.Generic.List<MotorState>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IrSensorStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"blocked")]
        public bool Blocked { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DribblerFeedbackStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"actual_force_n")]
        public float ActualForceN { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PowerStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"v5_voltage")]
        public float V5Voltage { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"v5_current")]
        public float V5Current { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"v5_energy")]
        public float V5Energy { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"v24_voltage")]
        public float V24Voltage { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"v24_current")]
        public float V24Current { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"v24_energy")]
        public float V24Energy { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MikonaStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"charging")]
        public bool Charging { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"discharging")]
        public bool Discharging { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"done")]
        public bool Done { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"voltage")]
        public float Voltage { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"fault")]
        public bool Fault { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"fault_invalid_cmd")]
        public bool FaultInvalidCmd { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"fault_charge_timeout")]
        public bool FaultChargeTimeout { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"fault_discharge_stuck")]
        public bool FaultDischargeStuck { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"fault_kick_a_no_drop")]
        public bool FaultKickANoDrop { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"fault_kick_b_no_drop")]
        public bool FaultKickBNoDrop { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RobotInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"robot_id")]
        public uint RobotId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"dip", IsPacked = true)]
        public bool[] Dips { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"button")]
        public bool Button { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DriverDiag : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"fault_pin")]
        public bool FaultPin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reset")]
        public bool Reset { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"drv_otpw")]
        public bool DrvOtpw { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"drv_ot")]
        public bool DrvOt { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"uv_cp")]
        public bool UvCp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"shortdet_u")]
        public bool ShortdetU { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"s2vsu")]
        public bool S2vsu { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"shortdet_v")]
        public bool ShortdetV { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"s2gv")]
        public bool S2gv { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"s2vsv")]
        public bool S2vsv { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"shortdet_w")]
        public bool ShortdetW { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"s2vsw")]
        public bool S2vsw { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"drv_en")]
        public bool DrvEn { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"otpw")]
        public bool Otpw { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"ot136c")]
        public bool Ot136c { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"ot143c")]
        public bool Ot143c { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"ot150c")]
        public bool Ot150c { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"version")]
        public uint Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ControllerDiag : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"status_pin")]
        public bool StatusPin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pid_x_target_limit")]
        public bool PidXTargetLimit { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"pid_x_target_ddt_limit")]
        public bool PidXTargetDdtLimit { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"pid_x_errsum_limit")]
        public bool PidXErrsumLimit { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"pid_x_output_limit")]
        public bool PidXOutputLimit { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"pid_v_target_limit")]
        public bool PidVTargetLimit { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"pid_v_target_ddt_limit")]
        public bool PidVTargetDdtLimit { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"pid_v_errsum_limit")]
        public bool PidVErrsumLimit { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"pid_v_output_limit")]
        public bool PidVOutputLimit { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"pid_id_target_limit")]
        public bool PidIdTargetLimit { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"pid_id_target_ddt_limit")]
        public bool PidIdTargetDdtLimit { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"pid_id_errsum_limit")]
        public bool PidIdErrsumLimit { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"pid_id_output_limit")]
        public bool PidIdOutputLimit { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"pid_iq_target_limit")]
        public bool PidIqTargetLimit { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"pid_iq_target_ddt_limit")]
        public bool PidIqTargetDdtLimit { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"pid_iq_errsum_limit")]
        public bool PidIqErrsumLimit { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"pid_iq_output_limit")]
        public bool PidIqOutputLimit { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"ipark_cirlim_u_d")]
        public bool IparkCirlimUD { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"ipark_cirlim_u_q")]
        public bool IparkCirlimUQ { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"ipark_cirlim_u_r")]
        public bool IparkCirlimUR { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"pwm_min")]
        public bool PwmMin { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"pwm_max")]
        public bool PwmMax { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"adc_i_clipped")]
        public bool AdcIClipped { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"ref_sw_r")]
        public bool RefSwR { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"ref_sw_h")]
        public bool RefSwH { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"ref_sw_l")]
        public bool RefSwL { get; set; }

        [global::ProtoBuf.ProtoMember(27, Name = @"not_pll_locked")]
        public bool NotPllLocked { get; set; }

        [global::ProtoBuf.ProtoMember(28, Name = @"wd_error")]
        public bool WdError { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MotorDiag : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"controller_ok")]
        public bool ControllerOk { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"driver_ok")]
        public bool DriverOk { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"driver")]
        public DriverDiag Driver { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"controller")]
        public ControllerDiag Controller { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DiagStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"imu_connected")]
        public bool ImuConnected { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"imu_temp")]
        public float ImuTemp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"motors")]
        public global::System.Collections.Generic.List<MotorDiag> Motors { get; } = new global::System.Collections.Generic.List<MotorDiag>();

        [global::ProtoBuf.ProtoMember(4, Name = @"mikona_connected")]
        public bool MikonaConnected { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"mikona_fault")]
        public bool MikonaFault { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"iter_ms")]
        public float IterMs { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"micro_ms")]
        public float MicroMs { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"imu_ms")]
        public float ImuMs { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"motors_ms")]
        public float MotorsMs { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"ssid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ssid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"hostname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Hostname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ip { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MotorCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"motor_id")]
        public MotorId MotorId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"motion_mode")]
        public MotionMode MotionMode { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"value")]
        public float Value { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"use_physical_dribbler_command")]
        public bool UsePhysicalDribblerCommand { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"surface_speed_mm_per_s")]
        public float SurfaceSpeedMmPerS { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"torque_limit_nm")]
        public float TorqueLimitNm { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MotorCommandBatch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"commands")]
        public global::System.Collections.Generic.List<MotorCommand> Commands { get; } = new global::System.Collections.Generic.List<MotorCommand>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MikonaCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"charge")]
        public bool Charge { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"discharge")]
        public bool Discharge { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clear_fault")]
        public bool ClearFault { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KickCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public KickType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"power")]
        public float Power { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"require_ball")]
        public bool RequireBall { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MotorEnableCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"enable")]
        public bool Enable { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuzzerCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sequence")]
        public BuzzerSequence Sequence { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RobotCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"halted")]
        public bool Halted { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"vx")]
        public float Vx { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"vy")]
        public float Vy { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"current_angle")]
        public float CurrentAngle { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"target_angle")]
        public float TargetAngle { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"shoot")]
        public float Shoot { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"chip")]
        public float Chip { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"dribbler_speed")]
        public float DribblerSpeed { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"dribbler_force")]
        public float DribblerForce { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum MotionMode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"MOTION_MODE_UNKNOWN")]
        MotionModeUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MOTION_MODE_VELOCITY")]
        MotionModeVelocity = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"MOTION_MODE_POSITION")]
        MotionModePosition = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"MOTION_MODE_TORQUE")]
        MotionModeTorque = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"MOTION_MODE_STOPPED")]
        MotionModeStopped = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MotorId
    {
        [global::ProtoBuf.ProtoEnum(Name = @"MOTOR_ID_MD")]
        MotorIdMd = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MOTOR_ID_M1")]
        MotorIdM1 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"MOTOR_ID_M2")]
        MotorIdM2 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"MOTOR_ID_M3")]
        MotorIdM3 = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"MOTOR_ID_M4")]
        MotorIdM4 = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum KickType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"KICK_TYPE_A")]
        KickTypeA = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"KICK_TYPE_B")]
        KickTypeB = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum BuzzerSequence
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_NONE")]
        BuzzerSequenceNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_BOOT_JINGLE")]
        BuzzerSequenceBootJingle = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_TRIPLE_ALERT")]
        BuzzerSequenceTripleAlert = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_CHIRP")]
        BuzzerSequenceChirp = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_SAD_TROMBONE")]
        BuzzerSequenceSadTrombone = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_MARIO_COIN")]
        BuzzerSequenceMarioCoin = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_MARIO_1UP")]
        BuzzerSequenceMario1up = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_ZELDA_ITEM_GET")]
        BuzzerSequenceZeldaItemGet = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_TETRIS")]
        BuzzerSequenceTetris = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"BUZZER_SEQUENCE_PAC_MAN_DEATH")]
        BuzzerSequencePacManDeath = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum StatusTopic
    {
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_TOPIC_IMU")]
        StatusTopicImu = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_TOPIC_MOTORS")]
        StatusTopicMotors = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_TOPIC_POWER")]
        StatusTopicPower = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_TOPIC_MIKONA")]
        StatusTopicMikona = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_TOPIC_INFO")]
        StatusTopicInfo = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_TOPIC_DIAG")]
        StatusTopicDiag = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_TOPIC_IR_SENSOR")]
        StatusTopicIrSensor = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_TOPIC_DRIBBLER_FEEDBACK")]
        StatusTopicDribblerFeedback = 7,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CommandType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"COMMAND_TYPE_MOTOR")]
        CommandTypeMotor = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"COMMAND_TYPE_MIKONA")]
        CommandTypeMikona = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"COMMAND_TYPE_KICK")]
        CommandTypeKick = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"COMMAND_TYPE_MOTOR_ENABLE")]
        CommandTypeMotorEnable = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"COMMAND_TYPE_BUZZER")]
        CommandTypeBuzzer = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"COMMAND_TYPE_ROBOT")]
        CommandTypeRobot = 5,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
