using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tyr.SourceGen;

[Generator]
public class GlobalsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ClassDeclarationSyntax> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetClassIfHasGenerateGlobals(ctx))
            .Where(static m => m is not null)!;

        // every [Configurable] type of this assembly, registered from the module initializer
        var configurables = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ConfigurableModel.ConfigurableAttributeName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => ConfigurableModel.FullName((INamedTypeSymbol)ctx.TargetSymbol))
            .Collect()
            .Select(static (names, _) => names.OrderBy(static n => n, StringComparer.Ordinal).ToImmutableArray());

        context.RegisterSourceOutput(classDeclarations.Combine(configurables), static (spc, pair) =>
            GenerateGlobals(spc, pair.Left, pair.Right));
    }

    private static ClassDeclarationSyntax? GetClassIfHasGenerateGlobals(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);
        if (symbol is null) return null;

        return symbol.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == typeof(GenerateGlobalsAttribute).FullName)
            ? classDecl
            : null;
    }

    private static void GenerateGlobals(SourceProductionContext context, ClassDeclarationSyntax classDecl,
        ImmutableArray<string> configurables)
    {
        // Derive namespace from syntax (avoids needing the semantic model here)
        string ns = GetNamespace(classDecl);
        var nsParts = ns.Split('.');
        var moduleName = nsParts.LastOrDefault() ?? "Unknown";

        var registrations = new StringBuilder();
        foreach (var configurable in configurables)
        {
            registrations.Append("            Common.Config.Registry.Register(")
                .Append(configurable).AppendLine(".Configurable);");
        }

        var code = $$"""
                     // <auto-generated/>
                     #nullable enable

                     global using static Tyr.{{moduleName}}.Globals;
                     global using ZLogger;
                     global using Tyr.Common.Extensions;
                     global using Timestamp = Tyr.Common.Time.Timestamp;
                     using System.Runtime.CompilerServices;
                     using Microsoft.Extensions.Logging;

                     namespace {{ns}}
                     {
                         internal static class Globals
                         {
                             internal static string ModuleName => "{{moduleName}}";
                             internal static string? CallingModuleName => Common.Debug.ModuleContext.Current.Value;

                             private static bool UseCachedInstance => CallingModuleName == null || CallingModuleName == ModuleName;

                             internal static ILogger Log => UseCachedInstance ? _log : Common.Debug.Registry.GetLogger(CallingModuleName!);
                             internal static Common.Debug.Assertion.AssertProxy Assert => new(_assertResolver);
                             internal static Common.Debug.Drawing.Drawer Draw => UseCachedInstance ? _draw : Common.Debug.Registry.GetDrawer(CallingModuleName!);
                             internal static Common.Debug.Plotting.Plotter Plot => UseCachedInstance ? _plot : Common.Debug.Registry.GetPlotter(CallingModuleName!);
                             internal static Random Rand { get; private set; } = null!;

                             // cached owned instances to avoid registry lookups
                             private static ILogger _log = null!;
                             private static Common.Debug.Assertion.Assert _assert = null!;
                             private static readonly Func<Common.Debug.Assertion.Assert> _assertResolver = ResolveAssert;
                             private static Common.Debug.Drawing.Drawer _draw = null!;
                             private static Common.Debug.Plotting.Plotter _plot = null!;

                             private static Common.Debug.Assertion.Assert ResolveAssert()
                             {
                                 var callingModuleName = Common.Debug.ModuleContext.Current.Value;
                                 return callingModuleName == null || callingModuleName == ModuleName
                                     ? _assert
                                     : Common.Debug.Registry.GetAssert(callingModuleName);
                             }

                             [ModuleInitializer]
                             internal static void Init()
                             {
                                 _log = Common.Debug.Registry.GetLogger(ModuleName);
                                 _assert = Common.Debug.Registry.GetAssert(ModuleName);
                                 _draw = Common.Debug.Registry.GetDrawer(ModuleName);
                                 _plot = Common.Debug.Registry.GetPlotter(ModuleName);

                                 Rand = new Random();

                                 // register this assembly's configurables; storages loaded before this point replay their values onto them
                     {{registrations}}                             }
                         }
                     }
                     """;

        context.AddSource("Globals.g.cs", SourceText.From(code, Encoding.UTF8));
    }

    private static string GetNamespace(ClassDeclarationSyntax classDecl)
    {
        SyntaxNode? parent = classDecl.Parent;
        while (parent != null)
        {
            if (parent is NamespaceDeclarationSyntax ns)
                return ns.Name.ToString();
            if (parent is FileScopedNamespaceDeclarationSyntax fns)
                return fns.Name.ToString();
            parent = parent.Parent;
        }
        return string.Empty;
    }
}
