<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Tyr.Gui</RootNamespace>
        <AssemblyName>Tyr.Gui</AssemblyName>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>14</LangVersion>
        <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj"/>
        <ProjectReference Include="..\Control\Control.csproj"/>
        <ProjectReference Include="..\Referee\Referee.csproj"/>
        <ProjectReference Include="..\Sender\Sender.csproj" />
        <ProjectReference Include="..\Soccer\Soccer.csproj"/>
        <ProjectReference Include="..\Vision\Vision.csproj"/>
        <ProjectReference Include="..\SourceGen\SourceGen.csproj" OutputItemType="Analyzer"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
      <PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
      <PackageReference Include="Hexa.NET.ImGui.Backends.SDL3" Version="1.0.18" />
      <PackageReference Include="Hexa.NET.ImPlot" Version="2.2.9" />
      <PackageReference Include="Hexa.NET.OpenGL3" Version="1.1.0" />
      <PackageReference Include="Hexa.NET.SDL3" Version="1.2.17" />
      <PackageReference Include="NativeFileDialogSharp" Version="0.5.0" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Fonts\fa-solid-900.ttf" />
      <EmbeddedResource Include="Fonts\seguiemj.ttf" />
      <EmbeddedResource Include="Fonts\InterVariable.ttf" />
      <EmbeddedResource Include="Fonts\JetBrainsMono[wght].ttf" />
      <EmbeddedResource Include="Assets\AppIcon.png" />
    </ItemGroup>

    <ItemGroup>
      <None Include="Assets\AppIcon.ico" />
      <None Include="Assets\AppIcon.icns" />
    </ItemGroup>

</Project>
