<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Tyr.Soccer</RootNamespace>
        <AssemblyName>Tyr.Soccer</AssemblyName>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj"/>
        <ProjectReference Include="..\Sender\Sender.csproj"/>
        <ProjectReference Include="..\SourceGen\SourceGen.csproj" OutputItemType="Analyzer"/>
    </ItemGroup>

</Project>
