<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Tyr.Common</RootNamespace>
        <AssemblyName>Tyr.Common</AssemblyName>
        <IsPackable>false</IsPackable>
        <LangVersion>14</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LightningDB" Version="0.21.0" />
      <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
      <PackageReference Include="MemoryPack" Version="1.21.4" />
      <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="NetMQ" Version="4.0.2.2" />
      <PackageReference Include="NumFlat" Version="1.2.3" />
      <PackageReference Include="protobuf-net" Version="3.2.56" />
      <PackageReference Include="Samboy063.Tomlet" Version="6.2.0" />
      <PackageReference Include="ZLogger" Version="2.5.10" />
      <PackageReference Include="ZString" Version="2.6.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="BannedSymbols.txt" />
      <AdditionalFiles Include="BannedSymbols.txt" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SourceGen\SourceGen.csproj" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
