using Tyr.Common.Math;

namespace Tyr.Common.Data.Ssl.Gc;

// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS8625, CS8603, CS8618, CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192

[global::ProtoBuf.ProtoContract()]
public partial class GameEvent : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(50, Name = @"id")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Id
    {
        get => __pbn__Id ?? "";
        set => __pbn__Id = value;
    }
    public bool ShouldSerializeId() => __pbn__Id != null;
    public void ResetId() => __pbn__Id = null;
    private string __pbn__Id;

    [global::ProtoBuf.ProtoMember(40)]
    [global::System.ComponentModel.DefaultValue(Type.UnknownGameEventType)]
    public Type type
    {
        get => __pbn__type ?? Type.UnknownGameEventType;
        set => __pbn__type = value;
    }
    public bool ShouldSerializetype() => __pbn__type != null;
    public void Resettype() => __pbn__type = null;
    private Type? __pbn__type;

    [global::ProtoBuf.ProtoMember(41, Name = @"origin")]
    public global::System.Collections.Generic.List<string> Origins { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(49, Name = @"created_timestamp")]
    public ulong CreatedTimestamp
    {
        get => __pbn__CreatedTimestamp.GetValueOrDefault();
        set => __pbn__CreatedTimestamp = value;
    }
    public bool ShouldSerializeCreatedTimestamp() => __pbn__CreatedTimestamp != null;
    public void ResetCreatedTimestamp() => __pbn__CreatedTimestamp = null;
    private ulong? __pbn__CreatedTimestamp;

    [global::ProtoBuf.ProtoMember(6, Name = @"ball_left_field_touch_line")]
    public BallLeftField BallLeftFieldTouchLine
    {
        get => __pbn__event.Is(6) ? ((BallLeftField)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
    }
    public bool ShouldSerializeBallLeftFieldTouchLine() => __pbn__event.Is(6);
    public void ResetBallLeftFieldTouchLine() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 6);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__event;

    [global::ProtoBuf.ProtoMember(7, Name = @"ball_left_field_goal_line")]
    public BallLeftField BallLeftFieldGoalLine
    {
        get => __pbn__event.Is(7) ? ((BallLeftField)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
    }
    public bool ShouldSerializeBallLeftFieldGoalLine() => __pbn__event.Is(7);
    public void ResetBallLeftFieldGoalLine() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 7);

    [global::ProtoBuf.ProtoMember(11)]
    public AimlessKick aimless_kick
    {
        get => __pbn__event.Is(11) ? ((AimlessKick)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(11, value);
    }
    public bool ShouldSerializeaimless_kick() => __pbn__event.Is(11);
    public void Resetaimless_kick() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 11);

    [global::ProtoBuf.ProtoMember(19)]
    public AttackerTooCloseToDefenseArea attacker_too_close_to_defense_area
    {
        get => __pbn__event.Is(19) ? ((AttackerTooCloseToDefenseArea)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(19, value);
    }
    public bool ShouldSerializeattacker_too_close_to_defense_area() => __pbn__event.Is(19);
    public void Resetattacker_too_close_to_defense_area() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 19);

    [global::ProtoBuf.ProtoMember(31)]
    public DefenderInDefenseArea defender_in_defense_area
    {
        get => __pbn__event.Is(31) ? ((DefenderInDefenseArea)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(31, value);
    }
    public bool ShouldSerializedefender_in_defense_area() => __pbn__event.Is(31);
    public void Resetdefender_in_defense_area() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 31);

    [global::ProtoBuf.ProtoMember(43)]
    public BoundaryCrossing boundary_crossing
    {
        get => __pbn__event.Is(43) ? ((BoundaryCrossing)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(43, value);
    }
    public bool ShouldSerializeboundary_crossing() => __pbn__event.Is(43);
    public void Resetboundary_crossing() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 43);

    [global::ProtoBuf.ProtoMember(13)]
    public KeeperHeldBall keeper_held_ball
    {
        get => __pbn__event.Is(13) ? ((KeeperHeldBall)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(13, value);
    }
    public bool ShouldSerializekeeper_held_ball() => __pbn__event.Is(13);
    public void Resetkeeper_held_ball() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 13);

    [global::ProtoBuf.ProtoMember(17)]
    public BotDribbledBallTooFar bot_dribbled_ball_too_far
    {
        get => __pbn__event.Is(17) ? ((BotDribbledBallTooFar)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(17, value);
    }
    public bool ShouldSerializebot_dribbled_ball_too_far() => __pbn__event.Is(17);
    public void Resetbot_dribbled_ball_too_far() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 17);

    [global::ProtoBuf.ProtoMember(24)]
    public BotPushedBot bot_pushed_bot
    {
        get => __pbn__event.Is(24) ? ((BotPushedBot)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(24, value);
    }
    public bool ShouldSerializebot_pushed_bot() => __pbn__event.Is(24);
    public void Resetbot_pushed_bot() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 24);

    [global::ProtoBuf.ProtoMember(26)]
    public BotHeldBallDeliberately bot_held_ball_deliberately
    {
        get => __pbn__event.Is(26) ? ((BotHeldBallDeliberately)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(26, value);
    }
    public bool ShouldSerializebot_held_ball_deliberately() => __pbn__event.Is(26);
    public void Resetbot_held_ball_deliberately() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 26);

    [global::ProtoBuf.ProtoMember(27)]
    public BotTippedOver bot_tipped_over
    {
        get => __pbn__event.Is(27) ? ((BotTippedOver)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(27, value);
    }
    public bool ShouldSerializebot_tipped_over() => __pbn__event.Is(27);
    public void Resetbot_tipped_over() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 27);

    [global::ProtoBuf.ProtoMember(51)]
    public BotDroppedParts bot_dropped_parts
    {
        get => __pbn__event.Is(51) ? ((BotDroppedParts)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(51, value);
    }
    public bool ShouldSerializebot_dropped_parts() => __pbn__event.Is(51);
    public void Resetbot_dropped_parts() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 51);

    [global::ProtoBuf.ProtoMember(15)]
    public AttackerTouchedBallInDefenseArea attacker_touched_ball_in_defense_area
    {
        get => __pbn__event.Is(15) ? ((AttackerTouchedBallInDefenseArea)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(15, value);
    }
    public bool ShouldSerializeattacker_touched_ball_in_defense_area() => __pbn__event.Is(15);
    public void Resetattacker_touched_ball_in_defense_area() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 15);

    [global::ProtoBuf.ProtoMember(18)]
    public BotKickedBallTooFast bot_kicked_ball_too_fast
    {
        get => __pbn__event.Is(18) ? ((BotKickedBallTooFast)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(18, value);
    }
    public bool ShouldSerializebot_kicked_ball_too_fast() => __pbn__event.Is(18);
    public void Resetbot_kicked_ball_too_fast() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 18);

    [global::ProtoBuf.ProtoMember(22)]
    public BotCrashUnique bot_crash_unique
    {
        get => __pbn__event.Is(22) ? ((BotCrashUnique)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(22, value);
    }
    public bool ShouldSerializebot_crash_unique() => __pbn__event.Is(22);
    public void Resetbot_crash_unique() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 22);

    [global::ProtoBuf.ProtoMember(21)]
    public BotCrashDrawn bot_crash_drawn
    {
        get => __pbn__event.Is(21) ? ((BotCrashDrawn)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(21, value);
    }
    public bool ShouldSerializebot_crash_drawn() => __pbn__event.Is(21);
    public void Resetbot_crash_drawn() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 21);

    [global::ProtoBuf.ProtoMember(29)]
    public DefenderTooCloseToKickPoint defender_too_close_to_kick_point
    {
        get => __pbn__event.Is(29) ? ((DefenderTooCloseToKickPoint)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(29, value);
    }
    public bool ShouldSerializedefender_too_close_to_kick_point() => __pbn__event.Is(29);
    public void Resetdefender_too_close_to_kick_point() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 29);

    [global::ProtoBuf.ProtoMember(28)]
    public BotTooFastInStop bot_too_fast_in_stop
    {
        get => __pbn__event.Is(28) ? ((BotTooFastInStop)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(28, value);
    }
    public bool ShouldSerializebot_too_fast_in_stop() => __pbn__event.Is(28);
    public void Resetbot_too_fast_in_stop() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 28);

    [global::ProtoBuf.ProtoMember(20)]
    public BotInterferedPlacement bot_interfered_placement
    {
        get => __pbn__event.Is(20) ? ((BotInterferedPlacement)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(20, value);
    }
    public bool ShouldSerializebot_interfered_placement() => __pbn__event.Is(20);
    public void Resetbot_interfered_placement() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 20);

    [global::ProtoBuf.ProtoMember(39, Name = @"possible_goal")]
    public Goal PossibleGoal
    {
        get => __pbn__event.Is(39) ? ((Goal)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(39, value);
    }
    public bool ShouldSerializePossibleGoal() => __pbn__event.Is(39);
    public void ResetPossibleGoal() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 39);

    [global::ProtoBuf.ProtoMember(8)]
    public Goal goal
    {
        get => __pbn__event.Is(8) ? ((Goal)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
    }
    public bool ShouldSerializegoal() => __pbn__event.Is(8);
    public void Resetgoal() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 8);

    [global::ProtoBuf.ProtoMember(44, Name = @"invalid_goal")]
    public Goal InvalidGoal
    {
        get => __pbn__event.Is(44) ? ((Goal)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(44, value);
    }
    public bool ShouldSerializeInvalidGoal() => __pbn__event.Is(44);
    public void ResetInvalidGoal() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 44);

    [global::ProtoBuf.ProtoMember(14)]
    public AttackerDoubleTouchedBall attacker_double_touched_ball
    {
        get => __pbn__event.Is(14) ? ((AttackerDoubleTouchedBall)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(14, value);
    }
    public bool ShouldSerializeattacker_double_touched_ball() => __pbn__event.Is(14);
    public void Resetattacker_double_touched_ball() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 14);

    [global::ProtoBuf.ProtoMember(5)]
    public PlacementSucceeded placement_succeeded
    {
        get => __pbn__event.Is(5) ? ((PlacementSucceeded)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
    }
    public bool ShouldSerializeplacement_succeeded() => __pbn__event.Is(5);
    public void Resetplacement_succeeded() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 5);

    [global::ProtoBuf.ProtoMember(45)]
    public PenaltyKickFailed penalty_kick_failed
    {
        get => __pbn__event.Is(45) ? ((PenaltyKickFailed)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(45, value);
    }
    public bool ShouldSerializepenalty_kick_failed() => __pbn__event.Is(45);
    public void Resetpenalty_kick_failed() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 45);

    [global::ProtoBuf.ProtoMember(2)]
    public NoProgressInGame no_progress_in_game
    {
        get => __pbn__event.Is(2) ? ((NoProgressInGame)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeno_progress_in_game() => __pbn__event.Is(2);
    public void Resetno_progress_in_game() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 2);

    [global::ProtoBuf.ProtoMember(3)]
    public PlacementFailed placement_failed
    {
        get => __pbn__event.Is(3) ? ((PlacementFailed)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializeplacement_failed() => __pbn__event.Is(3);
    public void Resetplacement_failed() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 3);

    [global::ProtoBuf.ProtoMember(32)]
    public MultipleCards multiple_cards
    {
        get => __pbn__event.Is(32) ? ((MultipleCards)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(32, value);
    }
    public bool ShouldSerializemultiple_cards() => __pbn__event.Is(32);
    public void Resetmultiple_cards() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 32);

    [global::ProtoBuf.ProtoMember(34)]
    public MultipleFouls multiple_fouls
    {
        get => __pbn__event.Is(34) ? ((MultipleFouls)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(34, value);
    }
    public bool ShouldSerializemultiple_fouls() => __pbn__event.Is(34);
    public void Resetmultiple_fouls() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 34);

    [global::ProtoBuf.ProtoMember(37)]
    public BotSubstitution bot_substitution
    {
        get => __pbn__event.Is(37) ? ((BotSubstitution)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(37, value);
    }
    public bool ShouldSerializebot_substitution() => __pbn__event.Is(37);
    public void Resetbot_substitution() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 37);

    [global::ProtoBuf.ProtoMember(52)]
    public ExcessiveBotSubstitution excessive_bot_substitution
    {
        get => __pbn__event.Is(52) ? ((ExcessiveBotSubstitution)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(52, value);
    }
    public bool ShouldSerializeexcessive_bot_substitution() => __pbn__event.Is(52);
    public void Resetexcessive_bot_substitution() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 52);

    [global::ProtoBuf.ProtoMember(38)]
    public TooManyRobots too_many_robots
    {
        get => __pbn__event.Is(38) ? ((TooManyRobots)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(38, value);
    }
    public bool ShouldSerializetoo_many_robots() => __pbn__event.Is(38);
    public void Resettoo_many_robots() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 38);

    [global::ProtoBuf.ProtoMember(46)]
    public ChallengeFlag challenge_flag
    {
        get => __pbn__event.Is(46) ? ((ChallengeFlag)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(46, value);
    }
    public bool ShouldSerializechallenge_flag() => __pbn__event.Is(46);
    public void Resetchallenge_flag() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 46);

    [global::ProtoBuf.ProtoMember(48)]
    public ChallengeFlagHandled challenge_flag_handled
    {
        get => __pbn__event.Is(48) ? ((ChallengeFlagHandled)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(48, value);
    }
    public bool ShouldSerializechallenge_flag_handled() => __pbn__event.Is(48);
    public void Resetchallenge_flag_handled() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 48);

    [global::ProtoBuf.ProtoMember(47)]
    public EmergencyStop emergency_stop
    {
        get => __pbn__event.Is(47) ? ((EmergencyStop)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(47, value);
    }
    public bool ShouldSerializeemergency_stop() => __pbn__event.Is(47);
    public void Resetemergency_stop() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 47);

    [global::ProtoBuf.ProtoMember(35)]
    public UnsportingBehaviorMinor unsporting_behavior_minor
    {
        get => __pbn__event.Is(35) ? ((UnsportingBehaviorMinor)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(35, value);
    }
    public bool ShouldSerializeunsporting_behavior_minor() => __pbn__event.Is(35);
    public void Resetunsporting_behavior_minor() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 35);

    [global::ProtoBuf.ProtoMember(36)]
    public UnsportingBehaviorMajor unsporting_behavior_major
    {
        get => __pbn__event.Is(36) ? ((UnsportingBehaviorMajor)__pbn__event.Object) : default;
        set => __pbn__event = new global::ProtoBuf.DiscriminatedUnionObject(36, value);
    }
    public bool ShouldSerializeunsporting_behavior_major() => __pbn__event.Is(36);
    public void Resetunsporting_behavior_major() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event, 36);

    [global::ProtoBuf.ProtoContract()]
    public partial class BallLeftField : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AimlessKick : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"kick_location")]
        public Vector2 KickLocation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Goal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"kicking_team")]
        [global::System.ComponentModel.DefaultValue(Team.Unknown)]
        public Team KickingTeam
        {
            get => __pbn__KickingTeam ?? Team.Unknown;
            set => __pbn__KickingTeam = value;
        }
        public bool ShouldSerializeKickingTeam() => __pbn__KickingTeam != null;
        public void ResetKickingTeam() => __pbn__KickingTeam = null;
        private Team? __pbn__KickingTeam;

        [global::ProtoBuf.ProtoMember(2, Name = @"kicking_bot")]
        public uint KickingBot
        {
            get => __pbn__KickingBot.GetValueOrDefault();
            set => __pbn__KickingBot = value;
        }
        public bool ShouldSerializeKickingBot() => __pbn__KickingBot != null;
        public void ResetKickingBot() => __pbn__KickingBot = null;
        private uint? __pbn__KickingBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"kick_location")]
        public Vector2 KickLocation { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"max_ball_height")]
        public float MaxBallHeight
        {
            get => __pbn__MaxBallHeight.GetValueOrDefault();
            set => __pbn__MaxBallHeight = value;
        }
        public bool ShouldSerializeMaxBallHeight() => __pbn__MaxBallHeight != null;
        public void ResetMaxBallHeight() => __pbn__MaxBallHeight = null;
        private float? __pbn__MaxBallHeight;

        [global::ProtoBuf.ProtoMember(7, Name = @"num_robots_by_team")]
        public uint NumRobotsByTeam
        {
            get => __pbn__NumRobotsByTeam.GetValueOrDefault();
            set => __pbn__NumRobotsByTeam = value;
        }
        public bool ShouldSerializeNumRobotsByTeam() => __pbn__NumRobotsByTeam != null;
        public void ResetNumRobotsByTeam() => __pbn__NumRobotsByTeam = null;
        private uint? __pbn__NumRobotsByTeam;

        [global::ProtoBuf.ProtoMember(8, Name = @"last_touch_by_team")]
        public ulong LastTouchByTeam
        {
            get => __pbn__LastTouchByTeam.GetValueOrDefault();
            set => __pbn__LastTouchByTeam = value;
        }
        public bool ShouldSerializeLastTouchByTeam() => __pbn__LastTouchByTeam != null;
        public void ResetLastTouchByTeam() => __pbn__LastTouchByTeam = null;
        private ulong? __pbn__LastTouchByTeam;

        [global::ProtoBuf.ProtoMember(9, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get => __pbn__Message ?? "";
            set => __pbn__Message = value;
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IndirectGoal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"kick_location")]
        public Vector2 KickLocation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChippedGoal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"kick_location")]
        public Vector2 KickLocation { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"max_ball_height")]
        public float MaxBallHeight
        {
            get => __pbn__MaxBallHeight.GetValueOrDefault();
            set => __pbn__MaxBallHeight = value;
        }
        public bool ShouldSerializeMaxBallHeight() => __pbn__MaxBallHeight != null;
        public void ResetMaxBallHeight() => __pbn__MaxBallHeight = null;
        private float? __pbn__MaxBallHeight;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotTooFastInStop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"speed")]
        public float Speed
        {
            get => __pbn__Speed.GetValueOrDefault();
            set => __pbn__Speed = value;
        }
        public bool ShouldSerializeSpeed() => __pbn__Speed != null;
        public void ResetSpeed() => __pbn__Speed = null;
        private float? __pbn__Speed;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DefenderTooCloseToKickPoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"distance")]
        public float Distance
        {
            get => __pbn__Distance.GetValueOrDefault();
            set => __pbn__Distance = value;
        }
        public bool ShouldSerializeDistance() => __pbn__Distance != null;
        public void ResetDistance() => __pbn__Distance = null;
        private float? __pbn__Distance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotCrashDrawn : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"bot_yellow")]
        public uint BotYellow
        {
            get => __pbn__BotYellow.GetValueOrDefault();
            set => __pbn__BotYellow = value;
        }
        public bool ShouldSerializeBotYellow() => __pbn__BotYellow != null;
        public void ResetBotYellow() => __pbn__BotYellow = null;
        private uint? __pbn__BotYellow;

        [global::ProtoBuf.ProtoMember(2, Name = @"bot_blue")]
        public uint BotBlue
        {
            get => __pbn__BotBlue.GetValueOrDefault();
            set => __pbn__BotBlue = value;
        }
        public bool ShouldSerializeBotBlue() => __pbn__BotBlue != null;
        public void ResetBotBlue() => __pbn__BotBlue = null;
        private uint? __pbn__BotBlue;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"crash_speed")]
        public float CrashSpeed
        {
            get => __pbn__CrashSpeed.GetValueOrDefault();
            set => __pbn__CrashSpeed = value;
        }
        public bool ShouldSerializeCrashSpeed() => __pbn__CrashSpeed != null;
        public void ResetCrashSpeed() => __pbn__CrashSpeed = null;
        private float? __pbn__CrashSpeed;

        [global::ProtoBuf.ProtoMember(5, Name = @"speed_diff")]
        public float SpeedDiff
        {
            get => __pbn__SpeedDiff.GetValueOrDefault();
            set => __pbn__SpeedDiff = value;
        }
        public bool ShouldSerializeSpeedDiff() => __pbn__SpeedDiff != null;
        public void ResetSpeedDiff() => __pbn__SpeedDiff = null;
        private float? __pbn__SpeedDiff;

        [global::ProtoBuf.ProtoMember(6, Name = @"crash_angle")]
        public float CrashAngle
        {
            get => __pbn__CrashAngle.GetValueOrDefault();
            set => __pbn__CrashAngle = value;
        }
        public bool ShouldSerializeCrashAngle() => __pbn__CrashAngle != null;
        public void ResetCrashAngle() => __pbn__CrashAngle = null;
        private float? __pbn__CrashAngle;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotCrashUnique : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"violator")]
        public uint Violator
        {
            get => __pbn__Violator.GetValueOrDefault();
            set => __pbn__Violator = value;
        }
        public bool ShouldSerializeViolator() => __pbn__Violator != null;
        public void ResetViolator() => __pbn__Violator = null;
        private uint? __pbn__Violator;

        [global::ProtoBuf.ProtoMember(3, Name = @"victim")]
        public uint Victim
        {
            get => __pbn__Victim.GetValueOrDefault();
            set => __pbn__Victim = value;
        }
        public bool ShouldSerializeVictim() => __pbn__Victim != null;
        public void ResetVictim() => __pbn__Victim = null;
        private uint? __pbn__Victim;

        [global::ProtoBuf.ProtoMember(4, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"crash_speed")]
        public float CrashSpeed
        {
            get => __pbn__CrashSpeed.GetValueOrDefault();
            set => __pbn__CrashSpeed = value;
        }
        public bool ShouldSerializeCrashSpeed() => __pbn__CrashSpeed != null;
        public void ResetCrashSpeed() => __pbn__CrashSpeed = null;
        private float? __pbn__CrashSpeed;

        [global::ProtoBuf.ProtoMember(6, Name = @"speed_diff")]
        public float SpeedDiff
        {
            get => __pbn__SpeedDiff.GetValueOrDefault();
            set => __pbn__SpeedDiff = value;
        }
        public bool ShouldSerializeSpeedDiff() => __pbn__SpeedDiff != null;
        public void ResetSpeedDiff() => __pbn__SpeedDiff = null;
        private float? __pbn__SpeedDiff;

        [global::ProtoBuf.ProtoMember(7, Name = @"crash_angle")]
        public float CrashAngle
        {
            get => __pbn__CrashAngle.GetValueOrDefault();
            set => __pbn__CrashAngle = value;
        }
        public bool ShouldSerializeCrashAngle() => __pbn__CrashAngle != null;
        public void ResetCrashAngle() => __pbn__CrashAngle = null;
        private float? __pbn__CrashAngle;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotPushedBot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"violator")]
        public uint Violator
        {
            get => __pbn__Violator.GetValueOrDefault();
            set => __pbn__Violator = value;
        }
        public bool ShouldSerializeViolator() => __pbn__Violator != null;
        public void ResetViolator() => __pbn__Violator = null;
        private uint? __pbn__Violator;

        [global::ProtoBuf.ProtoMember(3, Name = @"victim")]
        public uint Victim
        {
            get => __pbn__Victim.GetValueOrDefault();
            set => __pbn__Victim = value;
        }
        public bool ShouldSerializeVictim() => __pbn__Victim != null;
        public void ResetVictim() => __pbn__Victim = null;
        private uint? __pbn__Victim;

        [global::ProtoBuf.ProtoMember(4, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"pushed_distance")]
        public float PushedDistance
        {
            get => __pbn__PushedDistance.GetValueOrDefault();
            set => __pbn__PushedDistance = value;
        }
        public bool ShouldSerializePushedDistance() => __pbn__PushedDistance != null;
        public void ResetPushedDistance() => __pbn__PushedDistance = null;
        private float? __pbn__PushedDistance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotTippedOver : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ball_location")]
        public Vector2 BallLocation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotDroppedParts : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ball_location")]
        public Vector2 BallLocation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DefenderInDefenseArea : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"distance")]
        public float Distance
        {
            get => __pbn__Distance.GetValueOrDefault();
            set => __pbn__Distance = value;
        }
        public bool ShouldSerializeDistance() => __pbn__Distance != null;
        public void ResetDistance() => __pbn__Distance = null;
        private float? __pbn__Distance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DefenderInDefenseAreaPartially : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"distance")]
        public float Distance
        {
            get => __pbn__Distance.GetValueOrDefault();
            set => __pbn__Distance = value;
        }
        public bool ShouldSerializeDistance() => __pbn__Distance != null;
        public void ResetDistance() => __pbn__Distance = null;
        private float? __pbn__Distance;

        [global::ProtoBuf.ProtoMember(5, Name = @"ball_location")]
        public Vector2 BallLocation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AttackerTouchedBallInDefenseArea : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"distance")]
        public float Distance
        {
            get => __pbn__Distance.GetValueOrDefault();
            set => __pbn__Distance = value;
        }
        public bool ShouldSerializeDistance() => __pbn__Distance != null;
        public void ResetDistance() => __pbn__Distance = null;
        private float? __pbn__Distance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotKickedBallTooFast : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"initial_ball_speed")]
        public float InitialBallSpeed
        {
            get => __pbn__InitialBallSpeed.GetValueOrDefault();
            set => __pbn__InitialBallSpeed = value;
        }
        public bool ShouldSerializeInitialBallSpeed() => __pbn__InitialBallSpeed != null;
        public void ResetInitialBallSpeed() => __pbn__InitialBallSpeed = null;
        private float? __pbn__InitialBallSpeed;

        [global::ProtoBuf.ProtoMember(5, Name = @"chipped")]
        public bool Chipped
        {
            get => __pbn__Chipped.GetValueOrDefault();
            set => __pbn__Chipped = value;
        }
        public bool ShouldSerializeChipped() => __pbn__Chipped != null;
        public void ResetChipped() => __pbn__Chipped = null;
        private bool? __pbn__Chipped;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotDribbledBallTooFar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"start")]
        public Vector2 Start { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"end")]
        public Vector2 End { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AttackerTouchedOpponentInDefenseArea : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(4, Name = @"victim")]
        public uint Victim
        {
            get => __pbn__Victim.GetValueOrDefault();
            set => __pbn__Victim = value;
        }
        public bool ShouldSerializeVictim() => __pbn__Victim != null;
        public void ResetVictim() => __pbn__Victim = null;
        private uint? __pbn__Victim;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AttackerDoubleTouchedBall : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AttackerTooCloseToDefenseArea : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"distance")]
        public float Distance
        {
            get => __pbn__Distance.GetValueOrDefault();
            set => __pbn__Distance = value;
        }
        public bool ShouldSerializeDistance() => __pbn__Distance != null;
        public void ResetDistance() => __pbn__Distance = null;
        private float? __pbn__Distance;

        [global::ProtoBuf.ProtoMember(5, Name = @"ball_location")]
        public Vector2 BallLocation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotHeldBallDeliberately : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"duration")]
        public float Duration
        {
            get => __pbn__Duration.GetValueOrDefault();
            set => __pbn__Duration = value;
        }
        public bool ShouldSerializeDuration() => __pbn__Duration != null;
        public void ResetDuration() => __pbn__Duration = null;
        private float? __pbn__Duration;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotInterferedPlacement : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"by_bot")]
        public uint ByBot
        {
            get => __pbn__ByBot.GetValueOrDefault();
            set => __pbn__ByBot = value;
        }
        public bool ShouldSerializeByBot() => __pbn__ByBot != null;
        public void ResetByBot() => __pbn__ByBot = null;
        private uint? __pbn__ByBot;

        [global::ProtoBuf.ProtoMember(3, Name = @"location")]
        public Vector2 Location { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MultipleCards : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MultipleFouls : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"caused_game_events")]
        public global::System.Collections.Generic.List<GameEvent> CausedGameEvents { get; } = new global::System.Collections.Generic.List<GameEvent>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MultiplePlacementFailures : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KickTimeout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"time")]
        public float Time
        {
            get => __pbn__Time.GetValueOrDefault();
            set => __pbn__Time = value;
        }
        public bool ShouldSerializeTime() => __pbn__Time != null;
        public void ResetTime() => __pbn__Time = null;
        private float? __pbn__Time;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NoProgressInGame : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public float Time
        {
            get => __pbn__Time.GetValueOrDefault();
            set => __pbn__Time = value;
        }
        public bool ShouldSerializeTime() => __pbn__Time != null;
        public void ResetTime() => __pbn__Time = null;
        private float? __pbn__Time;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlacementFailed : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"remaining_distance")]
        public float RemainingDistance
        {
            get => __pbn__RemainingDistance.GetValueOrDefault();
            set => __pbn__RemainingDistance = value;
        }
        public bool ShouldSerializeRemainingDistance() => __pbn__RemainingDistance != null;
        public void ResetRemainingDistance() => __pbn__RemainingDistance = null;
        private float? __pbn__RemainingDistance;

        [global::ProtoBuf.ProtoMember(3, Name = @"nearest_own_bot_distance")]
        public float NearestOwnBotDistance
        {
            get => __pbn__NearestOwnBotDistance.GetValueOrDefault();
            set => __pbn__NearestOwnBotDistance = value;
        }
        public bool ShouldSerializeNearestOwnBotDistance() => __pbn__NearestOwnBotDistance != null;
        public void ResetNearestOwnBotDistance() => __pbn__NearestOwnBotDistance = null;
        private float? __pbn__NearestOwnBotDistance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsportingBehaviorMinor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason", IsRequired = true)]
        public string Reason { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsportingBehaviorMajor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason", IsRequired = true)]
        public string Reason { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeeperHeldBall : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"duration")]
        public float Duration
        {
            get => __pbn__Duration.GetValueOrDefault();
            set => __pbn__Duration = value;
        }
        public bool ShouldSerializeDuration() => __pbn__Duration != null;
        public void ResetDuration() => __pbn__Duration = null;
        private float? __pbn__Duration;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlacementSucceeded : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time_taken")]
        public float TimeTaken
        {
            get => __pbn__TimeTaken.GetValueOrDefault();
            set => __pbn__TimeTaken = value;
        }
        public bool ShouldSerializeTimeTaken() => __pbn__TimeTaken != null;
        public void ResetTimeTaken() => __pbn__TimeTaken = null;
        private float? __pbn__TimeTaken;

        [global::ProtoBuf.ProtoMember(3, Name = @"precision")]
        public float Precision
        {
            get => __pbn__Precision.GetValueOrDefault();
            set => __pbn__Precision = value;
        }
        public bool ShouldSerializePrecision() => __pbn__Precision != null;
        public void ResetPrecision() => __pbn__Precision = null;
        private float? __pbn__Precision;

        [global::ProtoBuf.ProtoMember(4, Name = @"distance")]
        public float Distance
        {
            get => __pbn__Distance.GetValueOrDefault();
            set => __pbn__Distance = value;
        }
        public bool ShouldSerializeDistance() => __pbn__Distance != null;
        public void ResetDistance() => __pbn__Distance = null;
        private float? __pbn__Distance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Prepared : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time_taken")]
        public float TimeTaken
        {
            get => __pbn__TimeTaken.GetValueOrDefault();
            set => __pbn__TimeTaken = value;
        }
        public bool ShouldSerializeTimeTaken() => __pbn__TimeTaken != null;
        public void ResetTimeTaken() => __pbn__TimeTaken = null;
        private float? __pbn__TimeTaken;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BotSubstitution : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExcessiveBotSubstitution : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeFlag : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeFlagHandled : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"accepted", IsRequired = true)]
        public bool Accepted { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EmergencyStop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TooManyRobots : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num_robots_allowed")]
        public int NumRobotsAllowed
        {
            get => __pbn__NumRobotsAllowed.GetValueOrDefault();
            set => __pbn__NumRobotsAllowed = value;
        }
        public bool ShouldSerializeNumRobotsAllowed() => __pbn__NumRobotsAllowed != null;
        public void ResetNumRobotsAllowed() => __pbn__NumRobotsAllowed = null;
        private int? __pbn__NumRobotsAllowed;

        [global::ProtoBuf.ProtoMember(3, Name = @"num_robots_on_field")]
        public int NumRobotsOnField
        {
            get => __pbn__NumRobotsOnField.GetValueOrDefault();
            set => __pbn__NumRobotsOnField = value;
        }
        public bool ShouldSerializeNumRobotsOnField() => __pbn__NumRobotsOnField != null;
        public void ResetNumRobotsOnField() => __pbn__NumRobotsOnField = null;
        private int? __pbn__NumRobotsOnField;

        [global::ProtoBuf.ProtoMember(4, Name = @"ball_location")]
        public Vector2 BallLocation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BoundaryCrossing : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"location")]
        public Vector2 Location { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PenaltyKickFailed : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"by_team", IsRequired = true)]
        public Team ByTeam { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"location")]
        public Vector2 Location { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason
        {
            get => __pbn__Reason ?? "";
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private string __pbn__Reason;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Type
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_GAME_EVENT_TYPE")]
        UnknownGameEventType = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BALL_LEFT_FIELD_TOUCH_LINE")]
        BallLeftFieldTouchLine = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"BALL_LEFT_FIELD_GOAL_LINE")]
        BallLeftFieldGoalLine = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"AIMLESS_KICK")]
        AimlessKick = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA")]
        AttackerTooCloseToDefenseArea = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"DEFENDER_IN_DEFENSE_AREA")]
        DefenderInDefenseArea = 31,
        [global::ProtoBuf.ProtoEnum(Name = @"BOUNDARY_CROSSING")]
        BoundaryCrossing = 41,
        [global::ProtoBuf.ProtoEnum(Name = @"KEEPER_HELD_BALL")]
        KeeperHeldBall = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_DRIBBLED_BALL_TOO_FAR")]
        BotDribbledBallTooFar = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_PUSHED_BOT")]
        BotPushedBot = 24,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_HELD_BALL_DELIBERATELY")]
        BotHeldBallDeliberately = 26,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_TIPPED_OVER")]
        BotTippedOver = 27,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_DROPPED_PARTS")]
        BotDroppedParts = 47,
        [global::ProtoBuf.ProtoEnum(Name = @"ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA")]
        AttackerTouchedBallInDefenseArea = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_KICKED_BALL_TOO_FAST")]
        BotKickedBallTooFast = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_CRASH_UNIQUE")]
        BotCrashUnique = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_CRASH_DRAWN")]
        BotCrashDrawn = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"DEFENDER_TOO_CLOSE_TO_KICK_POINT")]
        DefenderTooCloseToKickPoint = 29,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_TOO_FAST_IN_STOP")]
        BotTooFastInStop = 28,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_INTERFERED_PLACEMENT")]
        BotInterferedPlacement = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"EXCESSIVE_BOT_SUBSTITUTION")]
        ExcessiveBotSubstitution = 48,
        [global::ProtoBuf.ProtoEnum(Name = @"POSSIBLE_GOAL")]
        PossibleGoal = 39,
        [global::ProtoBuf.ProtoEnum(Name = @"GOAL")]
        Goal = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_GOAL")]
        InvalidGoal = 42,
        [global::ProtoBuf.ProtoEnum(Name = @"ATTACKER_DOUBLE_TOUCHED_BALL")]
        AttackerDoubleTouchedBall = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"PLACEMENT_SUCCEEDED")]
        PlacementSucceeded = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"PENALTY_KICK_FAILED")]
        PenaltyKickFailed = 43,
        [global::ProtoBuf.ProtoEnum(Name = @"NO_PROGRESS_IN_GAME")]
        NoProgressInGame = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PLACEMENT_FAILED")]
        PlacementFailed = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"MULTIPLE_CARDS")]
        MultipleCards = 32,
        [global::ProtoBuf.ProtoEnum(Name = @"MULTIPLE_FOULS")]
        MultipleFouls = 34,
        [global::ProtoBuf.ProtoEnum(Name = @"BOT_SUBSTITUTION")]
        BotSubstitution = 37,
        [global::ProtoBuf.ProtoEnum(Name = @"TOO_MANY_ROBOTS")]
        TooManyRobots = 38,
        [global::ProtoBuf.ProtoEnum(Name = @"CHALLENGE_FLAG")]
        ChallengeFlag = 44,
        [global::ProtoBuf.ProtoEnum(Name = @"CHALLENGE_FLAG_HANDLED")]
        ChallengeFlagHandled = 46,
        [global::ProtoBuf.ProtoEnum(Name = @"EMERGENCY_STOP")]
        EmergencyStop = 45,
        [global::ProtoBuf.ProtoEnum(Name = @"UNSPORTING_BEHAVIOR_MINOR")]
        UnsportingBehaviorMinor = 35,
        [global::ProtoBuf.ProtoEnum(Name = @"UNSPORTING_BEHAVIOR_MAJOR")]
        UnsportingBehaviorMajor = 36,
    }

}

#pragma warning restore CS8625, CS8603, CS8618, CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
